### ISSUE TITLE
Box plot does not need "stderr"

### ISSUE THREAD

**Issue by carleshf** [inab/OEB_level2_data_migration#7]
Box-plot visualization do not need "stderr" so it should not be mandatory to have on the metric-value block.

An idea for the update of the tools could be (`catalogs.py`):
```python
            # add assessment metrics values, as inline data
            if "value" in min_d_metrics:
                metric_value = min_d_metrics["value"]
                if "stderr" in min_d_metrics.keys():      # start the update
                    error_value = min_d_metrics["stderr"] # .
                else:                                     # .
                    error_value = None                    # end the update
                datalink_payload = {
                    "schema_url": SINGLE_METRIC_SCHEMA_ID,
                    "inline_data": {
                        "value": metric_value,
                        "error": error_value,
                    }
                }
```

**Comment by carleshf** [comment]
It might be better to make the "stderr" non mandatory in the schema (`single-metric.json`):

```json
        "required": [
                "value",
                "error"
        ],
```

**Comment by jmfernandez** [comment]
Hi @carleshf , I have just pushed the first batch of changes at 4b46a99e00d5bc99f56a713c493b31c262530b8c . An additional change could be applied later, related to always assigning a 0 error value when `error` does not appear.

Could you give it a try, please?

**Comment by carleshf** [comment]
@jmfernandez It seems the issue with error is now covered but it raised an exception elsewhere:

```
2023-07-12 22:10:55 trenzalore oeb_level2.process.assessment::AssessmentBuilder
[INFO] 
	==================================
	4. Generating Metrics Events
	==================================

Traceback (most recent call last):
  File "/.../OEB_level2_data_migration/push_data_to_oeb.py", line 16, in <module>
    main()
  File "/.../OEB_level2_data_migration/oeb_level2/main/push_data_to_oeb.py", line 733, in main
    validate_transform_and_push(
  File "/.../OEB_level2_data_migration/oeb_level2/main/push_data_to_oeb.py", line 584, in validate_transform_and_push
    valid_metrics_events = process_assessments.build_metrics_events(
  File "/.../OEB_level2_data_migration/oeb_level2/process/assessment.py", line 353, in build_metrics_events
    tool_id = dataset["depends_on"]["tool_id"]
KeyError: 'tool_id'
```
